-- V001 baseline: estrutura principal (multi-tenant, soft-delete, historico)

CREATE TABLE LAYOUT_VERSION (
  VERSION_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TENANT_ID    VARCHAR2(60) DEFAULT 'default' NOT NULL,
  LABEL        VARCHAR2(100) NOT NULL,
  STATUS       VARCHAR2(20)  DEFAULT 'ACTIVE'
                 CONSTRAINT CK_LV_STATUS CHECK (STATUS IN ('DRAFT','ACTIVE','RETIRED')),
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE REGISTRO (
  ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TENANT_ID      VARCHAR2(60) DEFAULT 'default' NOT NULL,
  CPF            VARCHAR2(11)  NOT NULL,
  NOME           VARCHAR2(200) NOT NULL,
  EMAIL          VARCHAR2(200),
  LAYOUT_VERSION NUMBER NOT NULL,
  ATTRS          JSON,
  ROW_VERSION    NUMBER DEFAULT 1 NOT NULL,
  DELETED        NUMBER(1) DEFAULT 0 CONSTRAINT CK_REG_DEL CHECK (DELETED IN (0,1)),
  DELETED_AT     TIMESTAMP,
  DELETED_BY     VARCHAR2(120),
  STATUS         VARCHAR2(20) DEFAULT 'ACTIVE',
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_REGISTRO_CPF UNIQUE (TENANT_ID, CPF),
  CONSTRAINT FK_REGISTRO_LV FOREIGN KEY (LAYOUT_VERSION) REFERENCES LAYOUT_VERSION(VERSION_ID)
);

CREATE TABLE REGISTRO_HISTORY (
  HISTORY_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REGISTRO_ID  NUMBER NOT NULL,
  TENANT_ID    VARCHAR2(60) NOT NULL,
  VERSION_NO   NUMBER NOT NULL,
  OPERATION    VARCHAR2(10) NOT NULL
                 CONSTRAINT CK_HIST_OP CHECK (OPERATION IN ('CREATE','UPDATE','DELETE')),
  SNAPSHOT     JSON,
  CHANGED_BY   VARCHAR2(120) DEFAULT 'anonimo' NOT NULL,
  CHANGED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE FIELD_METADATA (
  FIELD_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TENANT_ID      VARCHAR2(60) DEFAULT 'default' NOT NULL,
  LAYOUT_VERSION NUMBER NOT NULL,
  LOGICAL_NAME   VARCHAR2(100) NOT NULL,
  JSON_PATH      VARCHAR2(200),
  STORAGE        VARCHAR2(10) NOT NULL
                   CONSTRAINT CK_FM_STORAGE CHECK (STORAGE IN ('CORE','DYNAMIC')),
  DATA_TYPE      VARCHAR2(20) NOT NULL
                   CONSTRAINT CK_FM_TYPE CHECK (DATA_TYPE IN ('STRING','NUMBER','BOOLEAN','DATE','ARRAY','OBJECT')),
  ITEM_TYPE      VARCHAR2(20)
                   CONSTRAINT CK_FM_ITEM CHECK (ITEM_TYPE IS NULL OR ITEM_TYPE IN ('STRING','NUMBER','BOOLEAN','DATE')),
  REQUIRED       NUMBER(1) DEFAULT 0 CONSTRAINT CK_FM_REQ CHECK (REQUIRED IN (0,1)),
  VISIBLE        NUMBER(1) DEFAULT 1 CONSTRAINT CK_FM_VIS CHECK (VISIBLE IN (0,1)),
  EDITABLE       NUMBER(1) DEFAULT 1 CONSTRAINT CK_FM_EDT CHECK (EDITABLE IN (0,1)),
  SENSITIVE      NUMBER(1) DEFAULT 0 CONSTRAINT CK_FM_SENS CHECK (SENSITIVE IN (0,1)),
  MASK_STYLE     VARCHAR2(20)
                   CONSTRAINT CK_FM_MASK CHECK (MASK_STYLE IS NULL OR MASK_STYLE IN ('cpf','email','partial','full')),
  DISPLAY_ORDER  NUMBER DEFAULT 100,
  LABEL          VARCHAR2(200) NOT NULL,
  LABEL_I18N     JSON,
  SECTION        VARCHAR2(100),
  VALIDATION     JSON,
  VISIBLE_WHEN   JSON,
  ACTIVE         NUMBER(1) DEFAULT 1 CONSTRAINT CK_FM_ACT CHECK (ACTIVE IN (0,1)),
  CONSTRAINT UQ_FIELD UNIQUE (LAYOUT_VERSION, LOGICAL_NAME),
  CONSTRAINT FK_FM_LV FOREIGN KEY (LAYOUT_VERSION) REFERENCES LAYOUT_VERSION(VERSION_ID)
);
