-- V002 indices (tenant, historico, campo dinamico quente, multivalue de array)

CREATE INDEX IX_REG_TENANT ON REGISTRO (TENANT_ID, DELETED);

CREATE INDEX IX_HIST_REG ON REGISTRO_HISTORY (REGISTRO_ID, VERSION_NO);

CREATE INDEX IX_REG_RENDA
  ON REGISTRO (JSON_VALUE(ATTRS, '$.rendaMensal' RETURNING NUMBER));

CREATE MULTIVALUE INDEX IX_REG_TELEFONES
  ON REGISTRO r (r.ATTRS.telefones[*].string());
