-- V003 governanca: campos ignorados

CREATE TABLE IGNORED_FIELDS (
  IGNORED_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TENANT_ID      VARCHAR2(60) DEFAULT 'default' NOT NULL,
  LAYOUT_VERSION NUMBER NOT NULL,
  LOGICAL_NAME   VARCHAR2(100) NOT NULL,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_IGNORED UNIQUE (LAYOUT_VERSION, LOGICAL_NAME),
  CONSTRAINT FK_IGN_LV FOREIGN KEY (LAYOUT_VERSION) REFERENCES LAYOUT_VERSION(VERSION_ID)
);
