-- V004 auditoria (append-only)

CREATE TABLE AUDIT_LOG (
  AUDIT_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TS         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  TENANT_ID  VARCHAR2(60) DEFAULT 'default' NOT NULL,
  ACTOR      VARCHAR2(120) DEFAULT 'anonimo' NOT NULL,
  ACTION     VARCHAR2(40)  NOT NULL,
  ENTITY     VARCHAR2(40)  NOT NULL,
  ENTITY_ID  VARCHAR2(100),
  DETAILS    JSON
);

CREATE INDEX IX_AUDIT_ENTITY ON AUDIT_LOG (TENANT_ID, ENTITY, ENTITY_ID);
CREATE INDEX IX_AUDIT_TS     ON AUDIT_LOG (TS DESC);
