-- V008 segundo tenant de demonstracao ('acme') para provar isolamento multi-tenant/VPD.
-- Usuario admin (senha admin123, mesmo hash bcrypt do tenant default).

INSERT INTO LAYOUT_VERSION (TENANT_ID, LABEL, STATUS) VALUES ('acme', 'Acme v1', 'ACTIVE');

INSERT INTO FIELD_METADATA (TENANT_ID, LAYOUT_VERSION, LOGICAL_NAME, JSON_PATH, STORAGE, DATA_TYPE,
       REQUIRED, VISIBLE, EDITABLE, SENSITIVE, MASK_STYLE, DISPLAY_ORDER, LABEL)
VALUES ('acme', (SELECT VERSION_ID FROM LAYOUT_VERSION WHERE TENANT_ID='acme' AND LABEL='Acme v1'),
       'cpf', NULL, 'CORE', 'STRING', 1, 1, 1, 1, 'cpf', 10, 'CPF');

INSERT INTO FIELD_METADATA (TENANT_ID, LAYOUT_VERSION, LOGICAL_NAME, JSON_PATH, STORAGE, DATA_TYPE,
       REQUIRED, VISIBLE, EDITABLE, SENSITIVE, MASK_STYLE, DISPLAY_ORDER, LABEL)
VALUES ('acme', (SELECT VERSION_ID FROM LAYOUT_VERSION WHERE TENANT_ID='acme' AND LABEL='Acme v1'),
       'nome', NULL, 'CORE', 'STRING', 1, 1, 1, 0, NULL, 20, 'Nome');

INSERT INTO APP_USER (TENANT_ID, USERNAME, PASSWORD_HASH, ROLES) VALUES
  ('acme', 'admin', '$2b$10$PStTKUDTyuNiMZlnVFmHKe5kaCw6DL9aTIgUTNmQwv4C7nUf3WJEG', 'admin,editor,viewer,pii');
